---
###############################################################################
# NFS server variables.
###############################################################################
nfs_directories:
  - { "server": "{{ nfs_server }}",
      "src": /permabit/not-backed-up,
      "dest": /permabit/not-backed-up }

nfs_exports: "{{ nfs_directories + user_homes }}"
