---
_kernel_selection:
  distribution: "{{ ansible_distribution + ansible_distribution_version }}"
  architecture: "{{ ansible_machine }}"
  environment:

_kernel_packages:
  # Common to all distributions.
  - common:
    - kernel-devel
    - kernel-headers
    - kernel-tools

  ##########################################################################
  # Fedora
  ##########################################################################
  # grubby isn't a kernel package per se, but we need it for the processing
  # the kernel_packages role performs.

  # Common to all Fedora starting with Fedora28.
  - Fedora([1-9][0-9]{2,}|2[8-9]|[3-9][0-9]):
    - grubby
    - kernel-core
    - kernel-modules

  # Add kernel package to CentOS, RHEL and Fedora before Fedora41
  # since kernel package is not avaiable after Fedora40.
  - Fedora(2[8-9]|3[0-9]|40):
    - kernel

  - (CentOS|RedHat)(?![1-7]\.[0-9]+)[1-9][0-9]*\.[0-9]+:
    - kernel

  ##########################################################################
  # Architecture-specific.
  ##########################################################################
  - architecture:
    - aarch64:
      - common:
        - kernel-debug
        - kernel-debug-devel
        - kernel-tools-libs

      # Common to all Fedora starting with Fedora28.
      - Fedora([1-9][0-9]{2,}|2[8-9]|[3-9][0-9]):
        - kernel-debug-core

    - ppc64le:
      - common:
        - kernel-tools-libs

    - s390x:

    - x86_64:
      - common:
        - kernel-debug
        - kernel-debug-devel
        - kernel-tools-libs

      # Common to all Fedora starting with Fedora28.
      - Fedora([1-9][0-9]{2,}|2[8-9]|[3-9][0-9]):
        - kernel-debug-core

kernel_packages: "{{ _kernel_packages | select_install(_kernel_selection) }}"
