---
# Always start from a fresh copy so that we have a known good starting point.
- name: Copy proper perl Config template into place
  shell: cp -vf /usr/share/perl5/vendor_perl/Permabit/perl.yaml /etc/permabit/perl.yaml
  become: yes

- name: Configure Permabit::RSVP in perl.yaml
  lineinfile:
    path: /etc/permabit/perl.yaml
    backrefs: yes
    regexp: '^(\s*)[#]?{{ item.key }}: .*'
    line: '\1{{ item.key }}: {{ item.value }}'
  become: yes
  with_items:
    - { key: "defaultRSVPServer", value: "{{ rsvp_server }}" }

- name: Add environmental config values to affected perl.yaml entries
  replace:
    path: /etc/permabit/perl.yaml
    regexp: '{{ regexBegin }}{{ regexEnd }}'
    replace: '\1{{ addEntries }}'
  become: yes
  vars:
    regexBegin: '(?s)^({{ item.keyPath[:-1] | join(":.+?") }}:.+?\n'
    regexEnd: '(\s+){{ item.keyPath[-1] }}:\n)'
    addEntries: '\2  - {{ item.entries | join("\n\2  - ") }}\n'
  with_items:
    - { keyPath: ["Permabit::RSVP", "config", "processes", "ok", "user"],
        entries: ["ssh .* sftp", "sshfs"] }
  when: is_devvm | bool
