---
- name: Check lib journald.conf
  stat:
    path: /usr/lib/systemd/journald.conf
  register: has_lib_journald_conf

- name: Copy journald.conf
  ansible.builtin.copy:
    src: /usr/lib/systemd/journald.conf
    dest: /etc/systemd/journald.conf
    remote_src: yes
    force: false
  when: has_lib_journald_conf.stat.exists

- name: Update journald.conf
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "{{ item.pattern }}"
    line: "{{ item.line }}"
  with_items:
    - { pattern: "RateLimitIntervalSec=", line: "RateLimitIntervalSec=0s" }
    - { pattern: "Storage=",              line: "Storage=persistent" }
  register: journald_config
  become: yes

- name: Ensure persistent journal directory exists
  file:
    path: /var/log/journal
    state: directory
  register: journal_dir
  become: yes

- name: Fix persistent journal directory permissions
  command: "systemd-tmpfiles --create --prefix /var/log/journal"
  become: yes

- name: Flush journal
  command: "journalctl --flush"
  when: journal_dir is changed
  become: yes

- name: Reload journald configuration
  systemd:
    name: systemd-journald
    state: restarted
  when: journald_config is changed or journal_dir is changed
  become: yes
