---
- include_tasks: release_config_dir.yml

- name: Enable use of /proc/sysrq-trigger
  sysctl:
    name: kernel.sysrq
    value: "1"
    sysctl_set: yes
  become: yes

- name: Enable crash dump on NMI
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: yes
  with_items:
    - kernel.panic_on_unrecovered_nmi
    - kernel.unknown_nmi_panic
  when: is_vagrant | bool
  become: yes

- name: Check lib system.conf
  stat:
    path: /usr/lib/systemd/system.conf
  register: has_lib_system_conf

- name: Copy system.conf
  ansible.builtin.copy:
    src: /usr/lib/systemd/system.conf
    dest: /etc/systemd/system.conf
    remote_src: yes
    force: false
  become: yes
  when: has_lib_system_conf.stat.exists

- name: Enable core dump generation
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: "^DefaultLimitCORE="
    state: present
    line: "DefaultLimitCORE=0:infinity"
  register: systemd_config
  become: yes

- name: Restart systemd and sshd to use new core dump setting
  systemd:
    name: sshd
    daemon_reexec: yes
    state: restarted
  when: systemd_config is changed
  become: yes

- name: Enable sysstat monitoring
  systemd:
    name: sysstat
    state: started
    enabled: yes
  become: yes

- name: Ensure distro VDO package lock directory is not present
  file:
    path: /var/lock/vdo
    state: absent
  become: yes
