---
- block:

  - name: Get installed package list
    package_facts:

  - name: Check for packages with multiple versions
    assert:
      that: "{{ dups|length == 0 }}"
      msg: "multiple versions of packages installed: \
              {{ dups | sort | join(', ') }}"
    vars:
      dups: |
        {%- set x = [] -%}
        {%- for pkgname in ansible_facts.packages.keys()|sort(case_sensitive=True) -%}
          {%- set pkg = ansible_facts.packages[pkgname] -%}
          {%- if pkgname not in excludes -%}
            {%- set y = [] -%}
            {% for prefix in farm_ignore_packages -%}
              {%- if pkgname.startswith(prefix) -%}
                {%- set dummy = y.append(prefix) -%}
              {%- endif -%}
            {%- endfor -%}
            {%- if (y|length == 0) and (pkg|length > 1) -%}
              {%- set dummy = x.append(pkgname) -%}
            {%- endif -%}
          {%- endif -%}
        {%- endfor -%}
        {{ x }}

  - name: Build required_packages file
    template:
      src: required_packages
      dest: /etc/required_packages
      mode: 0644
      force: yes
    become: yes
    vars:
      newline: "\n"

  vars:
    excludes:
      - gpg-pubkey
      - gpm-libs
      - vim-common
      - vim-enhanced
