---
_early_selection:
  distribution: "{{ ansible_distribution + ansible_distribution_version }}"
  architecture: "{{ ansible_machine }}"
  environment:

_early_packages:
  ##########################################################################
  # Common to all distributions.
  ##########################################################################
  - common:

  ##########################################################################
  # Fedora
  ##########################################################################
  # Common to all Fedora starting with Fedora35.
  - Fedora([1-9][0-9]{2,}|3[5-9]|[4-9][0-9]):
    - python3-libselinux
    - python3-policycoreutils

  # Fedora 36 and up
  - Fedora([1-9][0-9]{2,}|3[6-9]|[4-9][0-9]):
    # 'acl' is required to allow us to deploy files as an unprivileged user for
    # another unprivileged user.
    - acl

  ##########################################################################
  # RHEL families
  ##########################################################################

  ##########################################################################
  # Environment-specific.
  ##########################################################################
  - environment:

  ##########################################################################
  # Architecture-specific.
  ##########################################################################
  - architecture:
    - aarch64:
    - ppc64le:
    - s390x:
    - x86_64:

early_packages: "{{ _early_packages | select_install(_early_selection) }}"
